<!DOCTYPE html>
<html lang="en">
    <head>
        
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="stylenav.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link rel="stylesheet" href="style.css">
        <link rel="shortcut icon" href="/img/favicon.ico">
        <title>RYACO | RyMail</title>
        
        
    </head>

    <body class="body2">
    <?php require_once "nav.php"; ?>

        <main class="main2">
            <div class="container2">
                <div class="container-p2">
                    <img src="img/Rx2.png" alt=""><p>RyMail</p>
                    <!-- <img src="img/ryaco-250x92.png" alt="" > -->
                </div>

                <div class="container-botones2">
                    <a href="categorias.php">Campañas</a>

                    <a href="categorias.php">Nueva Campaña</a>
                </div>
            </div>
        </main>
        
    </body>

</html>